name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # You can change this to any branch you prefer
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    
    - name: Build the Java project using Maven
      run: |
        mvn clean install
    

    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker Image to Docker Hub
      run: |
        # Generate a dynamic tag using Git commit hash (you can also use Git tags or timestamps)
        IMAGE_TAG="${GITHUB_SHA:0:7}"  # Get first 7 characters of the commit hash
        docker build -t gagan2104/cicd_poc:$IMAGE_TAG .
        docker push gagan2104/cicd_poc:$IMAGE_TAG

    - name: Checkout the helm-charts repository
      uses: actions/checkout@v3
      with:
        repository: saigagansatish/helm-charts  # Replace with your actual helm charts repository
        token: ${{ secrets.GITHUB_TOKEN }}
        path: helm-charts

    - name: Update image tag in Helm chart deployment file
      run: |
        IMAGE_TAG="${GITHUB_SHA:0:7}"  # Commit hash for the tag
        # Assuming your helm chart file is located in helm-charts/helm-manifests/deployment.yaml
        DEPLOYMENT_FILE=helm-charts/helm-manifests/deployment.yaml

        # Use 'yq' to edit the image tag in the YAML file
        # Ensure you have 'yq' installed
        yq e '.spec.template.spec.containers[0].image = "gagan2104/cicd_poc:'$IMAGE_TAG'"' -i $DEPLOYMENT_FILE

    - name: Commit and push changes to helm-charts repo
      run: |
        git config user.name "saigagansatish"
        git config user.email "gagan7876@gmail.com"
        git add helm-charts/helm-manifests/deployment.yaml
        git commit -m "Update image tag to $IMAGE_TAG"
        git push origin main  # Or the branch you're working on

   