name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # You can change this to any branch you prefer
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    
    - name: Build the Java project using Maven
      run: |
        mvn clean install
    
    - name: Build Docker Image
      run: |
        docker build -t your-dockerhub-username/my-java-app:latest .
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker Image to Docker Hub
      run: |
        docker push your-dockerhub-username/my-java-app:latest
